name: PlayerCheck
version: '${version}'
main: ru.meowland.PlayerCheck
api-version: 1.19
authors: [ KotMilkMeoW ]
description: meow

commands:
  callforcheck:
    permission: playercheck.callforcheck
  senddiscord:
    permission: playercheck.senddiscord
  canselcheck:
    permission: playercheck.canselcheck
